[package]
name = "openfga-dsl-parser"
version = "1.0.0"
edition = "2021"
license = "Apache-2.0 license"
description = "Parsing and JSON transformer for the OpenFGA authorization DSL"

[dependencies]
serde_json = "1.0"
